### ISSUE TITLE
Missing header file 'esp_wifi_internal.h' when compiling demo.ino

### ISSUE THREAD

**Issue by berrak** [RalphBacon/228-Wireless-Over-the-Air-OTA-ESP32-updates#1]
Hi, I tried your 'demo.ino', but encountered a compile issue in Arduino IDE 1.8.19 (Debian/Linux). Is this header file from the software development environment for the hardware based on the ESP32 chip by Espressif? Thus, do I need to set up Espressif IoT Development Framework?

Arduino: 1.8.19 (Linux), Board: "UM TinyPICO, Default, 921600, QIO, 80MHz, Enabled, None, Disabled"
/tmp/arduino_build_332910/sketch/demo.ino.cpp -o /dev/null
Alternatives for esp_wifi_internal.h: []
ResolveLibrary(esp_wifi_internal.h)
  -> candidates: []
Multiple libraries were found for "WiFi.h"
 Used: /home/bekr/.arduino15/packages/esp32/hardware/esp32/2.0.5/libraries/WiFi
 Not used: /home/bekr/Arduino/libraries/WiFiEspAT
 Not used: /opt/arduino-1.8.19/libraries/WiFi
In file included from /home/bekr/Arduino/SCRATCH-OTA-ESP32/228-Wireless-Over-the-Air-OTA-ESP32-updates/OTA_Include/demo/demo.ino:17:
Identification.h:10:10: fatal error: esp_wifi_internal.h: No such file or directory
 #include <esp_wifi_internal.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1
esp_wifi_internal.h: No such file or directory

**Comment by RalphBacon** [comment]
@berrak 
That library is used by Espressif themselves for displaying Wi-Fi-related logging/issues. You can comment that line out (and any others that depend on it) as it's only used for debugging purposes.

**Comment by berrak** [comment]
Hi Ralph,
Thanks for the quick reply.
I did that, and I'm underway to do the OTA thing. 
Cheers.

**Comment by berrak** [comment]
It works great; I will use it in my projects. Thanks for all your work. It's much appreciated. :-)

**Comment by RalphBacon** [comment]
I'm standing on the shoulders of giants, but still glad you're having success. Yes, I use all the time now too!

I'll close the issue as you have resolved your problem.
